version: '3.9'

services:
  db:
    container_name: postgres_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pg_database
      - POSTGRES_USER=yurii
      - POSTGRES_PASSWORD=12345
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yurii -d pg_database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped